package com.devterm.terminal.core.parser

sealed class ScreenCommand {
    data class WriteGlyph(val c: Char, val width: Int) : ScreenCommand()
    data class WriteString(val s: String) : ScreenCommand()
    data class MoveCursor(val row: Int, val col: Int) : ScreenCommand()
    data class CursorUp(val n: Int) : ScreenCommand()
    data class CursorDown(val n: Int) : ScreenCommand()
    data class CursorForward(val n: Int) : ScreenCommand()
    data class CursorBack(val n: Int) : ScreenCommand()
    data class SetCursorCol(val col: Int) : ScreenCommand()
    data class SetCursorRow(val row: Int) : ScreenCommand()
    object CarriageReturn : ScreenCommand()
    object LineFeed : ScreenCommand()
    object ReverseLineFeed : ScreenCommand()
    object ScrollUp : ScreenCommand()
    object ScrollDown : ScreenCommand()
    object Tab : ScreenCommand()
    data class EraseDisplay(val mode: Int) : ScreenCommand()
    data class EraseLine(val mode: Int) : ScreenCommand()
    data class EraseChars(val n: Int) : ScreenCommand()
    data class DeleteChars(val n: Int) : ScreenCommand()
    data class InsertLines(val n: Int) : ScreenCommand()
    data class DeleteLines(val n: Int) : ScreenCommand()
    data class InsertChars(val n: Int) : ScreenCommand()
    object SaveCursor : ScreenCommand()
    object RestoreCursor : ScreenCommand()
    object SetHorizontalTabStop : ScreenCommand()
    data class SetSgr(val params: List<Int>) : ScreenCommand()
    data class SetTitle(val title: String) : ScreenCommand()
    data class SetIconName(val name: String) : ScreenCommand()
    data class SetScrollRegion(val top: Int, val bottom: Int) : ScreenCommand()
    data class SetMode(val mode: Int, val set: Boolean) : ScreenCommand()
    data class SetPrivateMode(val mode: Int, val set: Boolean) : ScreenCommand()
    data class SetCursorStyle(val style: Int) : ScreenCommand()
    object Reset : ScreenCommand()
    data class Bell(val count: Int) : ScreenCommand()
    data class DeviceStatusReport(val n: Int) : ScreenCommand()
    data class CursorPositionReport(val row: Int, val col: Int) : ScreenCommand()
    object RequestCursorPosition : ScreenCommand()
}
